// src/adapters/react/watch.ts
import { useEffect, useRef } from "react";

/** Options for {@link useWatch}. */
export interface UseWatchOptions {
	/**
	 * Compare values deeply (via JSON serialization) instead of by reference.
	 * Defaults to `true`, matching the Vue adapter.
	 */
	deep?: boolean;
}

/**
 * React effect-based watcher that invokes `callback` whenever the value
 * produced by `source` changes. Tracks the previous value so the callback
 * receives `(value, previous)`.
 *
 * Runs once on mount (with `previous` undefined) and on every change. Cleans
 * up automatically on unmount.
 *
 * @typeParam T - The watched value type.
 * @param source - A getter returning the value to watch.
 * @param callback - Invoked on change as `(value, previous)`.
 * @param options - `deep` (default `true`) serializes objects for comparison.
 *
 * @example
 * ```tsx
 * import { useState } from "react";
 * import { useWatch } from "katanakit-js/adapters/react";
 *
 * function Form() {
 *   const [product, setProduct] = useState({ name: "", price: 0 });
 *   useWatch(() => product, (next, prev) => {
 *     console.log("changed:", next, prev);
 *   });
 *   // ...
 * }
 * ```
 */
export function useWatch<T>(
	source: () => T,
	callback: (value: T, previous: T | undefined) => void,
	options: UseWatchOptions = {},
): void {
	const { deep = true } = options;
	const previous = useRef<T | undefined>(undefined);
	const current = source();
	const dep = deep ? JSON.stringify(current) : current;

	useEffect(() => {
		callback(current, previous.current);
		previous.current = current;
	}, [dep]);
}

// src/adapters/solid/watch.ts
import { createEffect } from "solid-js";

/** Options for {@link useWatch}. Accepted for API parity; Solid tracks deep reads natively. */
export interface UseWatchOptions {
	deep?: boolean;
}

/**
 * Solid effect-based watcher that invokes `callback` whenever any signal read
 * inside `source` changes. Tracks the previous value so the callback receives
 * `(value, previous)`.
 *
 * Solid's fine-grained reactivity means nested mutations are tracked
 * automatically, so `deep` is effectively always on. Runs once on creation and
 * on every tracked change; cleans up with the owning component.
 *
 * @typeParam T - The watched value type.
 * @param source - A getter that reads the signals to watch.
 * @param callback - Invoked on change as `(value, previous)`.
 * @param options - Accepted for API parity (ignored).
 *
 * @example
 * ```tsx
 * import { createSignal } from "solid-js";
 * import { useWatch } from "katanakit-js/adapters/solid";
 *
 * function Form() {
 *   const [product, setProduct] = createSignal({ name: "", price: 0 });
 *   useWatch(() => product(), (next, prev) => console.log(next, prev));
 *   // ...
 * }
 * ```
 */
export function useWatch<T>(
	source: () => T,
	callback: (value: T, previous: T | undefined) => void,
	_options: UseWatchOptions = {},
): void {
	let previous: T | undefined;

	createEffect(() => {
		const value = source();
		callback(value, previous);
		previous = value;
	});
}
