// examples/notion/vue-blog.vue
<script setup lang="ts">
/**
 * Vue 3 SFC + Notion — blog listing from a Notion database.
 *
 * This file goes in: src/views/BlogView.vue
 *
 * Setup:
 *   1. Create a Notion integration at https://www.notion.so/my-integrations
 *   2. Share your database with the integration
 *   3. Add VITE_NOTION_TOKEN and VITE_NOTION_DATABASE_ID to .env
 *
 * Uses useQuery from katanakit-js/adapters/vue for reactive state
 * with caching and stale-while-revalidate.
 */

import { useQuery, useSafeQueryFn } from "katanakit-js/adapters/vue";
import { defineNotionConfig, useNotionListAllDatabasePages } from "katanakit-js/adapters/notion";
import type { NotionPage } from "katanakit-js/adapters/notion";

// Init once at module level
defineNotionConfig({ token: import.meta.env.VITE_NOTION_TOKEN });

// Reactive query — cached with stale-while-revalidate
const blog = useQuery({
	queryKey: ["notion-blog"],
	queryFn: useSafeQueryFn(() =>
		useNotionListAllDatabasePages(
			import.meta.env.VITE_NOTION_DATABASE_ID,
			{ property: "Status", select: { equals: "Published" } },
			[{ property: "Date", direction: "descending" }],
		),
	),
	staleTime: 60_000, // 1 minute
});

// Helper to extract title from Notion page properties
function getTitle(page: NotionPage): string {
	return (page.properties.Name as any)?.title?.[0]?.plain_text ?? "Untitled";
}

function getSlug(page: NotionPage): string {
	return (page.properties.Slug as any)?.rich_text?.[0]?.plain_text ?? page.id;
}

function getDate(page: NotionPage): string {
	return (page.properties.Date as any)?.date?.start ?? "";
}

function getStatus(page: NotionPage): string {
	return (page.properties.Status as any)?.select?.name ?? "";
}
</script>

<template>
	<div class="blog-listing">
		<h1>Blog</h1>
		<p>Powered by Notion + KatanaKit</p>

		<button @click="blog.refetch()" :disabled="blog.isFetching">
			{{ blog.isFetching ? "Loading..." : "Refresh" }}
		</button>

		<div v-if="blog.isPending" class="loading">Loading posts...</div>

		<div v-else-if="blog.error" class="error">
			<p>Error: {{ blog.error.message }}</p>
			<button @click="blog.refetch()">Retry</button>
		</div>

		<ul v-else-if="blog.data" class="post-list">
			<li v-for="page in blog.data" :key="page.id" class="post-item">
				<router-link :to="`/blog/${getSlug(page)}`">
					<strong>{{ getTitle(page) }}</strong>
				</router-link>

				<div class="meta">
					<time v-if="getDate(page)" :datetime="getDate(page)">
						{{ new Date(getDate(page)).toLocaleDateString() }}
					</time>
					<span v-if="getStatus(page)" class="badge">
						{{ getStatus(page) }}
					</span>
				</div>
			</li>
		</ul>

		<p v-else>No posts found.</p>
	</div>
</template>

<style scoped>
.blog-listing {
	max-width: 800px;
	margin: 0 auto;
	padding: 2rem;
}

.post-list {
	list-style: none;
	padding: 0;
}

.post-item {
	padding: 1rem 0;
	border-bottom: 1px solid #eee;
}

.meta {
	display: flex;
	gap: 0.5rem;
	margin-top: 0.25rem;
	color: #666;
	font-size: 0.875rem;
}

.badge {
	background: #e0e0ff;
	color: #333;
	padding: 0.125rem 0.5rem;
	border-radius: 1rem;
	font-size: 0.75rem;
}

.loading,
.error {
	padding: 2rem;
	text-align: center;
}

.error {
	color: #c00;
}
</style>

// examples/notion/next-blog.tsx
/**
 * Next.js (React) + Notion — blog listing from a Notion database.
 *
 * This file goes in: app/blog/page.tsx (App Router)
 *
 * Setup:
 *   1. Create a Notion integration at https://www.notion.so/my-integrations
 *   2. Share your database with the integration
 *   3. Add NOTION_TOKEN and NOTION_DATABASE_ID to .env.local
 */

import { defineNotionConfig, useNotionListAllDatabasePages } from "katanakit-js/adapters/notion";

// Init once at module level
defineNotionConfig({ token: process.env.NOTION_TOKEN! });

export default async function BlogPage() {
	// Fetch all published posts from Notion
	const posts = await useNotionListAllDatabasePages(
		process.env.NOTION_DATABASE_ID!,
		{ property: "Status", select: { equals: "Published" } },
		[{ property: "Date", direction: "descending" }],
	);

	if (!posts.ok) {
		return <div>Error: {posts.error.message}</div>;
	}

	return (
		<main>
			<h1>Blog — from Notion</h1>
			<p>Powered by Notion + KatanaKit</p>

			<ul>
				{posts.data.map((page) => {
					// Adjust property names to match your database schema
					const title = (page.properties.Name as any)?.title?.[0]?.plain_text ?? "Untitled";
					const status = (page.properties.Status as any)?.select?.name ?? "";
					const date = (page.properties.Date as any)?.date?.start ?? "";
					const slug = (page.properties.Slug as any)?.rich_text?.[0]?.plain_text ?? page.id;

					return (
						<li key={page.id}>
							<a href={`/blog/${slug}`}>
								<strong>{title}</strong>
							</a>
							{date && <time dateTime={date}>{new Date(date).toLocaleDateString()}</time>}
							{status && <span className="badge">{status}</span>}
						</li>
					);
				})}
			</ul>
		</main>
	);
}
